#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/10/19 15:26
# @Author  : Yao
# @Email   : 15927402897@163.com
# @project : RASER1.2

'''
改进：
数据库是每次抽取50题目
所以爬多次，筛选独立（没有出现过的）的题目
'''

from selenium import webdriver
from time import sleep
import os
#from selenium.webdriver.common.keys import Keys
#from selenium.webdriver.common.action_chains import ActionChains

def generate_question_database(paper_file):
    question_database = []
    QN = 0
    with open(paper_file, "r") as doc:
        for line in doc.readlines():
            if line.startswith(">"):
                question_database.append(line.strip("\n").split(".", 1)[1])
                QN += 1
    return question_database, QN

def main():
    global browser
    opt = webdriver.ChromeOptions()
    opt.set_headless()
    browser = webdriver.Chrome(options=opt)  
    # browser = webdriver.Chrome('/public/home/yxu/tools/chromedriver/chromedriver')

    #browser = webdriver.Chrome()

    log_in_url = '***'
    download_doc = 'F:/practice/'
    browser.get(log_in_url)
    user_name = browser.find_element_by_id('txtuserid').send_keys('***')  # 账号
    passwd = browser.find_element_by_id('txtpass').send_keys('***')  # 密码
    browser.find_element_by_xpath('//*[@id="Button1"]').click() # 登陆
    prictice_button = browser.find_element_by_xpath('//*[@id="t3"]/a') 
    browser.execute_script("$(arguments[0]).click()", prictice_button) 
    window=browser.window_handles 
    browser.switch_to_window(window[-1])  

    papar_name = []
    i = 1
    for ID in ("DataList1_ctl"+str(y)+"_HyperLink1" for y in (["0"+str(x) for x in range(10)]+[str(x) for x in range(10,20)])):
        papar_name.append(str(i) + browser.find_element_by_id(ID).text)
        i += 1

    def ElementExist(element, by):
        global browser
        if by == 'xpath':
            try:
                browser.find_element_by_xpath(element)
                return True
            except:
                return False

    paper_href_list = ['0'+str(x) for x in range(10)]
    paper_href_list += [str(x) for x in (10,11,12,13,14,20,21,22,23,24)]

    page = -1

    total_independent_question_num = 0

    for new_href in ('FLX.aspx?v='+x for x in paper_href_list):
        js = 'window.open("' + new_href + '");'
        browser.execute_script(js)
        window = browser.window_handles
        browser.switch_to_window(window[-1]) 
        page += 1
        print("page:%s" % papar_name[page])

        if os.path.exists(download_doc+papar_name[page]+'.txt'):
            question_database, QN = generate_question_database(download_doc+papar_name[page]+'.txt')
        else:
            question_database, QN = [], 0
        with open(download_doc+papar_name[page]+'.txt',"a+") as doc:
            a = browser.find_element_by_xpath('//*[@id="btnsubmit"]').click()
            alert = browser.switch_to_alert()  
            alert.accept()
            question_num = u'-1'
            next_question_num = u'0'
            while question_num != next_question_num:
                sleep(0.1)
                if ElementExist('//*[@id="lblnum"]','xpath'): 
                    question_num = browser.find_element_by_xpath('//*[@id="lblnum"]').text
                else:
                    print(browser.page_source)
                question = browser.find_element_by_xpath('//*[@id="lblquestion"]').text  
                if question.encode("utf-8") not in question_database:  
                    answer = browser.find_element_by_xpath('//*[@id="lb_answer"]').text 
                    option = {}
                    my_ASCCI = 65
                    test_xpath = ['//*[@id="RadioButtonList1"]/tbody/tr[1]/td/label', '//*[@id="CheckBoxList1"]/tbody/tr[1]/td/label']
                    if ElementExist(test_xpath[0],'xpath'):
                        for option_xpath in ('//*[@id="RadioButtonList1"]/tbody/tr[' + str(x) + ']/td/label' for x in range(1,10)):
                            if ElementExist(option_xpath, 'xpath'):
                                option[chr(my_ASCCI)]=browser.find_element_by_xpath(option_xpath).text
                                my_ASCCI += 1
                            else:
                                break
                    elif ElementExist(test_xpath[1],'xpath'):
                        for option_xpath in ('//*[@id="CheckBoxList1"]/tbody/tr[' + str(x) + ']/td/label' for x in range(1,10)):
                            if ElementExist(option_xpath,'xpath'):
                                option[chr(my_ASCCI)]=browser.find_element_by_xpath(option_xpath).text
                                my_ASCCI += 1
                            else:
                                break
                    else:
                        print "Warning: Others format!!"
                    total_independent_question_num += 1
                    # print question.encode("utf-8")
                    QN += 1
                    doc.writelines((">"+str(QN)+"."+question+"\n").encode("utf-8"))
                    for key in option:
                        doc.writelines(("\t"+key+"."+option[key]+"\n").encode("utf-8"))
                    doc.writelines(("\t\t"+answer+"\n\n").encode("utf-8"))
                browser.find_element_by_xpath('//*[@id="btnnext"]').click()
                if ElementExist('//*[@id="lblnum"]','xpath'): 
                    next_question_num = browser.find_element_by_xpath('//*[@id="lblnum"]').text
                else:
                    print(browser.page_source)
                next_question_num = browser.find_element_by_xpath('//*[@id="lblnum"]').text
    print("此次添加的题目个数为%d" % total_independent_question_num)
    return total_independent_question_num

if __name__ == '__main__':
    num = main()
    while num != 0:
        num = main()
